name: Selenium Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.12.2', '3.12.1', '3.12.0', '3.9.6']  
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest pytest-xdist
          pip install webdriver-manager
      
      - name: Run Selenium tests
        run: pytest server/test --browsers Firefox Chrome --headless
